app/controllers/BaseController.scala
app/controllers/LanguageController.scala
app/controllers/agent/AgentUnauthorisedForClientController.scala
app/controllers/agent/ConfirmClientVrnController.scala
app/controllers/agent/SelectClientVrnController.scala
app/controllers/predicates/AuthoriseAsAgentWithClient.scala
app/views/errors/agent/notAuthorisedForClient.scala.html
conf/app.routes
it/pages/agent/ConfirmClientVrnPageSpec.scala
test/controllers/agent/AgentUnauthorisedForClientControllerSpec.scala
test/controllers/agent/ConfirmClientVrnControllerSpec.scala
test/controllers/predicates/AuthoriseAsAgentWithClientSpec.scala
test/views/errors/agent/NotAuthorisedForClientViewSpec.scala

**Notes**
- Includes refactor of common method to a BaseController
- Includes refactor of some controller actions to remove unecessary async action on methods where no Futures were involved.

[add-redirectUrl-to-unauth-view] Add redirect url to unauth view

---

conf/prod.routes
it/helpers/IntegrationBaseSpec.scala

Make sure this is merged first:

BTAT-4381 Updated prod route

---

README.md

Deleted one line from the readme in order to test the recent changes to our deployment pipeline.

Line change to test deployment pipeline

---

conf/messages
test/assets/messages/BaseMessages.scala
test/views/errors/AccountMigrationViewSpec.scala
test/views/errors/NotSignedUpViewSpec.scala

Update the service name in the banner for Agents to ‘
Client's VAT details’ for VAT-agent-client-lookup

Update the service name in the banner for Agents to ‘Client's VAT details’ for VAT-agent-client-lookup

---

conf/messages.cy

Welsh messages added for vacluf

Welsh messages added for vacluf.

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/controllers/agent/CapturePreferenceController.scala
app/controllers/agent/ConfirmClientVrnController.scala
app/controllers/agent/ConfirmEmailController.scala
app/controllers/agent/SelectClientVrnController.scala
app/controllers/agent/VerifyEmailController.scala
app/controllers/agent/WhatToDoController.scala
app/controllers/predicates/PreferencePredicate.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf
it/helpers/IntegrationBaseSpec.scala
it/pages/agent/ConfirmEmailPageSpec.scala
it/pages/agent/SelectClientVrnPageSpec.scala
it/pages/agent/VerifyEmailPageSpec.scala
it/pages/agent/WhatToDoPageSpec.scala
test/controllers/agent/CapturePreferenceControllerSpec.scala
test/controllers/agent/ConfirmClientVrnControllerSpec.scala
test/controllers/agent/ConfirmEmailControllerSpec.scala
test/controllers/agent/SelectClientVrnControllerSpec.scala
test/controllers/agent/VerifyEmailControllerSpec.scala
test/controllers/agent/WhatToDoControllerSpec.scala
test/controllers/predicates/PreferencePredicateSpec.scala

APP CONFIG PRs
app-config-base: https://github.com/hmrc/app-config-base/pull/2561
app-config-prod: https://github.com/hmrc/app-config-production/pull/4486

BTAT-6760: Removed where to go agent action feature switch

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/controllers/BaseController.scala
app/controllers/agent/CapturePreferenceController.scala
app/controllers/agent/ConfirmClientVrnController.scala
app/controllers/agent/ConfirmEmailController.scala
app/controllers/agent/WhatToDoController.scala
app/controllers/predicates/PreferencePredicate.scala
conf/application.conf
test/controllers/agent/CapturePreferenceControllerSpec.scala
test/controllers/agent/ConfirmClientVrnControllerSpec.scala
test/controllers/agent/ConfirmEmailControllerSpec.scala
test/controllers/agent/SelectClientVrnControllerSpec.scala
test/controllers/agent/WhatToDoControllerSpec.scala
test/mocks/MockAppConfig.scala

APP CONFIG PR's
https://github.com/hmrc/app-config-production/pull/4547
https://github.com/hmrc/app-config-qa/pull/4786
https://github.com/hmrc/app-config-staging/pull/3251

BTAT-6760-new: Amended redirect url logic

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/models/RegistrationStatus.scala
app/views/agent/partials/registrationPartial.scala.html
build.sbt
conf/application.conf
conf/messages
conf/messages.cy
test/assets/messages/RegistrationPartialMessages.scala
test/mocks/MockAppConfig.scala
test/views/partials/RegistrationPartialSpec.scala

Added new registration section partial

---

app/controllers/agent/WhatToDoController.scala
it/helpers/IntegrationBaseSpec.scala
test/controllers/agent/AgentHubControllerSpec.scala
test/controllers/agent/WhatToDoControllerSpec.scala
test/mocks/MockAuth.scala

Don't merge until acceptance tests are updated to use the feature switch, or it will redirect every time

Added redirect logic to agent action page based off feature switch

---

app/config/frontendAppConfig.scala
app/controllers/agent/WhatToDoController.scala
app/views/agent/agentHub.scala.html
app/views/agent/partials/vatReturnsPartial.scala.html
conf/application.conf
test/controllers/agent/WhatToDoControllerSpec.scala
test/mocks/MockAppConfig.scala
test/views/agent/partials/VatReturnsPartialSpec.scala

Please ensure this is merged first:
https://github.com/hmrc/app-config-base/pull/3040

BTAT-7504 Updated submitted returns handoff URL following DAC changes

---

app/views/agent/CapturePreferenceView.scala.html
app/views/agent/SelectClientVrnView.scala.html
app/views/templates/inputs/text.scala.html
conf/messages
conf/messages.cy
it/pages/agent/SelectClientVrnPageSpec.scala
test/views/agent/SelectClientVrnViewSpec.scala
test/views/templates/inputs/TextTemplateSpec.scala

Also fixed:
- should be a gap between button and error line on email pref page
- field error messages should be bold

Fixed red line error display on client VRN page

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/forms/FeatureSwitchForm.scala
app/models/FeatureSwitchModel.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf

Not sure if we actually need these, but I've made them anyway:
https://github.com/hmrc/app-config-base/pull/3299
https://github.com/hmrc/app-config-production/pull/6225

[BTAT-7706] - feature switch for covid19 message

---

app/common/MandationStatus.scala
app/views/agent/partials/optOutForMTDVATPartial.scala.html
app/views/agent/partials/signUpPartial.scala.html
app/views/agent/partials/vatReturnsPartial.scala.html
conf/messages
test/assets/messages/partials/SignUpPartialMessages.scala
test/views/agent/partials/OptOutForMTDVATPartialSpec.scala
test/views/agent/partials/SignUpPartialSpec.scala

NOT TO BE MERGED UNTIL BULK PAPER STORY IS COMPLETE
To be merged alongside https://github.com/hmrc/change-vat-details-acceptance-tests/pull/105

BTAT-7792 - Added new mandation status

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/views/agent/AgentHubView.scala.html
app/views/agent/partials/Covid.scala.html
conf/application.conf
conf/messages
conf/messages.cy
public/stylesheets/vat.css
test/assets/messages/partials/CovidPartialMessages.scala
test/mocks/MockAppConfig.scala
test/views/agent/AgentHubViewSpec.scala
test/views/agent/partials/CovidPartialSpec.scala

Do not merge until Monday 15/06

BTAT-7926 Updated COVID banner for VAT payments deferral

---

app/views/agent/AgentHubView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/AgentHubMessages.scala
test/views/agent/AgentHubViewSpec.scala

Screenshot in story (and prototype) are not aligned to staging however I've confirmed with Lindsey that displaying it in this position is acceptable

BTAT-8293 Addition of message re client's DD/payment details

---

app/controllers/agent/ConfirmEmailController.scala
app/controllers/agent/VerifyEmailPinController.scala
app/views/agent/VerifyEmailPinView.scala.html
conf/app.routes
it/pages/agent/CheckYourAnswersPageSpec.scala
it/pages/agent/VerifyEmailPinPageSpec.scala
test/controllers/agent/ConfirmEmailControllerSpec.scala
test/controllers/agent/VerifyEmailPinControllerSpec.scala
test/mocks/services/MockEmailVerificationService.scala
test/views/agent/VerifyEmailPinViewSpec.scala

Reverts hmrc/vat-agent-client-lookup-frontend#190

Revert "[BTAT-8606] - wire up for new email verification"

---

app/testOnly/models/Passcode.scala

Unfortunately the email-verification readme also has incorrect JSON listed on it, so our JSON reads for this has to change.
I will also make a PR on the email-verification service to correct this.

BTAT-8607 Updated reads to account for new passcode test-only JSON

---

app/controllers/agent/ConfirmEmailController.scala
app/controllers/agent/VerifyEmailPinController.scala
app/views/agent/VerifyEmailPinView.scala.html
conf/app.routes
it/pages/agent/CheckYourAnswersPageSpec.scala
it/pages/agent/VerifyEmailPinPageSpec.scala
test/controllers/agent/ConfirmEmailControllerSpec.scala
test/controllers/agent/VerifyEmailPinControllerSpec.scala
test/mocks/services/MockEmailVerificationService.scala
test/views/agent/VerifyEmailPinViewSpec.scala

This re-applies the work done in BTAT-8606.

Reinstate BTAT-8606

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/connectors/DirectDebitConnector.scala
app/connectors/httpParsers/DirectDebitHttpParser.scala
app/models/DirectDebit.scala
app/services/DirectDebitService.scala
conf/application.conf
it/connectors/DirectDebitConnectorISpec.scala
it/helpers/IntegrationBaseSpec.scala
it/stubs/DirectDebitStub.scala
test/mocks/MockAppConfig.scala
test/models/DirectDebitSpec.scala
test/services/DirectDebitServiceSpec.scala

Please review and merge the following config PR too: https://github.com/hmrc/app-config-base/pull/5767

BTAT-9292 Added http/connector/service/model for DD call

---

app/views/errors/AccountMigrationView.scala.html
app/views/errors/NotSignedUpView.scala.html
app/views/errors/SessionTimeoutView.scala.html
app/views/errors/agent/IncorrectPasscodeView.scala.html
app/views/errors/agent/NotAuthorisedForClientView.scala.html
app/views/errors/agent/UnauthorisedNoEnrolmentView.scala.html
it/pages/agent/VerifyEmailPinPageSpec.scala
test/views/errors/AccountMigrationViewSpec.scala
test/views/errors/NotSignedUpViewSpec.scala
test/views/errors/SessionTimeoutViewSpec.scala
test/views/errors/agent/IncorrectPasscodeViewSpec.scala
test/views/errors/agent/NotAuthorisedForClientViewSpec.scala
test/views/errors/agent/UnauthorisedNoEnrolmentViewSpec.scala

AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/158

BTAT-9441 Updating error views to use govuk components

---

app/views/agent/DirectDebitInterruptView.scala.html
build.sbt
test/views/agent/DirectDebitInterruptViewSpec.scala

Please see the following AT PR as well: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/160

BTAT-9446 Migrated DirectDebitInterruptView to use GOVUK assets

---

app/views/agent/VerifyEmailPinView.scala.html
it/pages/agent/VerifyEmailPinPageSpec.scala
test/views/agent/VerifyEmailPinViewSpec.scala

AT PR: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/162

BTAT-9448 Moving VerifyEmailPin view to govuk assets

---

app/views/agent/CapturePreferenceView.scala.html
test/views/agent/CapturePreferenceViewSpec.scala

Please review together with the AT changes: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/164

Btat 9443 Upgraded CapturePreferenceView to new assets

---

app/controllers/agent/AgentHubController.scala
app/controllers/agent/DDInterruptController.scala
app/views/agent/AgentHubView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/AgentHubMessages.scala
test/controllers/agent/DDInterruptControllerSpec.scala
test/views/agent/AgentHubViewSpec.scala

Following a couple of chats with Bobby, the first sentence is now bigger and bold while the rest are standard `govuk-body` elements

[BTAT-9559] DD interrupt agent hub notification banner

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/config/frontendAppConfig.scala
app/connectors/PenaltiesConnector.scala
app/connectors/httpParsers/PenaltiesHttpParser.scala
app/forms/FeatureSwitchForm.scala
app/models/penalties/PenaltiesSummary.scala
app/services/PenaltiesService.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/views/featureSwitch/FeatureSwitchItems.scala
build.sbt
conf/application.conf
it/connectors/PenaltiesConnectorISpec.scala
it/helpers/IntegrationBaseSpec.scala
it/stubs/PenaltiesStub.scala
test/assets/PenaltiesConstants.scala
test/config/FeatureSpec.scala
test/connectors/PenaltiesConnectorSpec.scala
test/connectors/httpParsers/PenaltiesHttpParserSpec.scala
test/mocks/MockAppConfig.scala
test/models/penalties/PenaltiesSummarySpec.scala
test/services/PenaltiesServiceSpec.scala

App config base PR: https://github.com/hmrc/app-config-base/pull/6378

[BTAT-9823] - Added feature switch, service, connector and model for penalties connectivity

---

app/config/ConfigKeys.scala
app/config/frontendAppConfig.scala
app/connectors/httpParsers/PenaltiesHttpParser.scala
app/controllers/agent/AgentHubController.scala
app/testOnly/controllers/PenaltiesController.scala
app/testOnly/views/PenaltiesHomeView.scala.html
app/views/agent/AgentHubView.scala.html
app/views/agent/partials/PenaltiesTilePartial.scala.html
conf/application.conf
conf/messages
conf/testOnly.routes
test/assets/HubViewModelTestConstants.scala
test/assets/PenaltiesConstants.scala
test/assets/messages/partials/PenaltiesTileMessages.scala
test/connectors/httpParsers/PenaltiesHttpParserSpec.scala
test/controllers/agent/AgentHubControllerSpec.scala
test/mocks/MockAppConfig.scala
test/mocks/services/MockPenaltiesService.scala
test/views/agent/AgentHubViewSpec.scala
test/views/agent/partials/PenaltiesTilePartialSpec.scala

~Raising as draft until #240 is merged.~
See ticket to replicate.
https://user-images.githubusercontent.com/53828896/141084166-3b285bd6-653d-4d7e-b215-5f946ae456d9.mov

[BTAT-9855] - Added penalties tile

---

app/views/agent/AgentHubView.scala.html
app/views/helpers/MTDSignupNotificationBanner.scala.html
conf/messages
conf/messages.cy
test/views/agent/AgentHubViewSpec.scala
test/views/helpers/MTDSignupNotificationBannerSpec.scala

Please merge together with https://github.com/hmrc/change-vat-details-acceptance-tests/pull/198

[BTAT-10483] Added MTD sign up notification banner

---

app/views/helpers/DisplayDate.scala.html
conf/messages
conf/messages.cy
test/views/helpers/DisplayDateSpec.scala

This was another service that doesn't use short dates so I refactor the displayDate helper to remove the code that handles them.

BTAT-10600 Refactor of display date helper to use message file

---

app/views/agent/AgentHubView.scala.html
app/views/helpers/PenaltiesBanner.scala.html

I don't see any issues with the banner but found I could remove some custom margin styling as it has no effect due to the margin on the above element

BTAT-10958 Removed unnecessary styling from penalties banner

---

app/controllers/LanguageController.scala
build.sbt
it/helpers/IntegrationBaseSpec.scala
it/helpers/SessionCookieCrumbler.scala
project/plugins.sbt
test/forms/PreferenceFormSpec.scala
test/views/ViewBaseSpec.scala

Please merge with:
**Build-jobs PR:** https://github.com/hmrc/build-jobs/pull/12185
**Service-manager-config PR:** https://github.com/hmrc/service-manager-config/pull/4804

BTAT-11108 upgrade scala 2.13

---

app/audit/AuditService.scala
app/audit/models/AgentOverviewPageViewAuditModel.scala
app/controllers/agent/AgentHubController.scala
build.sbt
conf/application.conf
test/audit/models/AgentOverviewPageViewAuditModelSpec.scala
test/controllers/agent/AgentHubControllerSpec.scala

I didn't add an audit test to every scenario in the controller spec as most of them would be repeats. I focused on the scenarios where the audited information would differ, to verify the difference.
Tested locally with Wireshark

BTAT-11525 Added new audit event to overview page
